
$("#checkbox").click(function () {
    $(".numbers-button").toggleClass("button-dark");   
    $(".head-box").toggleClass("bac-dark1");  
    $(".main-box").toggleClass("bac-dark1");   
    $(".chest-box").toggleClass("bac-dark2");    
    $(".checkbox-label").toggleClass("bac-dark2");  
    $(".right-box ul li").toggleClass("button-dark");    
    $(".right-box ul").toggleClass("button-dark");    
    $(".right-box ul li button").toggleClass("button-dark");   
    $(".left-top-box li button").toggleClass("button-dark");   
    $(".head-box div button svg").toggleClass("text-dark");   

}) 
  


